github:
  user_or_org: nsls-ii-forge
channels:
  sources:
    - nsls2forge
    - defaults
  targets:
    - [nsls2forge, main]
channel_priority: flexible
provider:
  linux: azure
  osx: azure
  win: azure
upload_on_branch: master
azure:
  user_or_org: nsls2forge
  project_name: nsls2forge
## for local GPU runners
#  settings_linux:
#     pool:
#       name: BNL-machines
#       demands:
#         - gpu -equals true
#     workspace:
#       clean: all
#     strategy:
#       maxParallel: 2
#     # variables:
#     #   cutensor_path: /home/ci_agent/libcutensor_1.0.1/
#docker:
#   executable: docker
#   run_args: -t --rm --gpus all # -v $(cutensor_path):/home/conda/libcutensor:ro,z
